# Generated by Django 5.1.1 on 2024-09-09 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question/', verbose_name='이미지')),
                ('index', models.IntegerField(default=0, verbose_name='인덱스')),
                ('seconds', models.IntegerField(default=20, verbose_name='소요시간(초)')),
                ('score', models.IntegerField(default=1, verbose_name='점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '질문',
                'verbose_name_plural': '02. 질문',
                'db_table': 'questions',
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, null=True, verbose_name='설명')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnail/', verbose_name='썸네일')),
                ('engagement', models.IntegerField(default=0, verbose_name='참여수')),
                ('likes', models.IntegerField(default=0, verbose_name='좋아요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '테스트',
                'verbose_name_plural': '01. 테스트',
                'db_table': 'tests',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='selection/', verbose_name='이미지')),
                ('is_correct', models.BooleanField(default=False, verbose_name='정답')),
                ('index', models.IntegerField(default=0, verbose_name='인덱스')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection', to='quiz.question', verbose_name='질문')),
            ],
            options={
                'verbose_name': '선택지',
                'verbose_name_plural': '03. 선택지',
                'db_table': 'selections',
                'ordering': ['content'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz.test', verbose_name='테스트'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.UUIDField(blank=True, null=True, verbose_name='세션')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_answer', to='quiz.selection', verbose_name='선택지')),
            ],
            options={
                'verbose_name': '사용자 답변',
                'verbose_name_plural': '08. 사용자 답변',
                'db_table': 'user_answers',
            },
        ),
    ]
