# Generated by Django 5.1.1 on 2024-09-12 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_test_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selection',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='내용'),
        ),
    ]
